import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [info, setInfo] = useState("Hello");
  const [userInfo, setUserInfo] = useState("");
  const [userTimeInfo, setUserTimeInfo] = useState<any>("0:00:00");
  const hello = () => {
    if (info == "Hello") {
      setInfo("HelloWorld2");
    } else {
      setInfo("Hello");
    }
  };

  const getUserInfo = async () => {
    // const ur = await (
    //   await fetch("https://api.github.com/repos/Tomosuke0930/Yo/pulls/3")
    // ).json();
    // console.log(ur);
    // Get the all user's repository info

    const urs = await (
      await fetch("https://api.github.com/users/Tomosuke0930/repos")
    ).json();

    console.log(urs);

    // Get the all user's repository names
    const nameLists: string[] = new Array();
    const langLists: string[] = new Array();
    for (let i = 0; i < urs.length; i++) {
      nameLists.push(urs[i].name);
    }

    for (let i = 0; i < nameLists.length; i++) {
      // console.log("Moving Me!!!");
      const lang = await (
        await fetch(
          `https://api.github.com/repos/Tomosuke0930/${nameLists[i]}/languages`
        )
      ).json();
      // console.log(lang);
      langLists.push(lang);
    }
    console.log(langLists);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1>This is User Info</h1>
        <button onClick={getUserInfo}>Button</button>
        <h2>Language is {userInfo}</h2>
        <h2>Time is {userTimeInfo}</h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
